version: '3'

networks:
    backend:   

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        restart: unless-stopped
        networks:
            - backend
        depends_on: 
            - redis

    redis:
        image: redis
        ports:
            - "6379:6379"
        networks:
            - backend